### ISSUE TITLE
Rework KeyAgg algorithm to simplify Tweaking

### ISSUE THREAD

**Issue by jonasnick** [jonasnick/bips#12]
The following issue was discussed on the [mailing list](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-April/020372.html): To apply a tweaking scheme like Taproot, access to the internal key is required. Hence, one needs to call KeyAgg multiple times:
```
P := KeyAgg(pk1..u, <empty>, <empty>):
tweak := hash_TapTweak(P, root)
is_xonly_t := true
Q := KeyAgg(pk1..u, tweak, is_xonly_t):
```

Not only is this inefficient but it's also unintuitive to the point that no implementation that allows tweaking will implement KeyAgg as described in the spec. This is a good reason for changing the spec.

The most reasonable approach to me at this point is that we split the existing `KeyAgg` into a `KeyAgg` algoritm that only does key aggregation, `ApplyTweak` and `ApplyXonlyTweak` - similar to the libsecp-zkp API. The downside is that we need to expose the key aggregation state that was previously fully contained inside `KeyAgg`.

**Comment by real-or-random** [comment]
>  it's also unintuitive to the point that no implementation that allows tweaking will implement KeyAgg as described in the spec. This is a good reason for changing the spec.

I agree.

> The most reasonable approach to me at this point is that we split the existing `KeyAgg` into a `KeyAgg` algoritm that only does key aggregation, `ApplyTweak` and `ApplyXonlyTweak` - similar to the libsecp-zkp API. The downside is that we need to expose the key aggregation state that was previously fully contained inside `KeyAgg`.


Concept ACK.

**Comment by LLFourn** [comment]
I just went through my own redesign of this. Here's what I came up with:

1. Given a list of keys you get a `AggKey`. You can't sign or verify signatures with an `AggKey`.
2. You can apply tweaks to the `AggKey`. These are what the current spec calls "ordinary" tweaks.
3. You can convert the `AggKey` into a `Bip340AggKey`. You can do "xonly" tweaks on this but not "ordinary". You can only start a signing session with a `Bip340AggKey`.

Structuring things like this made things much more understandable compared to the spec compliant tweaking api we had before. I don't have a strong opinion on adopting the naming/structure I've chosen here in the spec but I do think that **the spec should forbid/discourge doing non-xonly tweaks after an xonly tweak**. This would guide implementations in a simpler direction and means there's less edge cases to spec test. I can't think of any reason you'd want an ordinary tweak after xonly tweak.

thoughts?

**Comment by jonasnick** [comment]
The approach in https://github.com/jonasnick/bips/pull/15 is as follows:

1. Given a list of keys you get a `keyagg_context`. You can't sign or verify signatures with a `keyagg_context`.
2. You can apply ordinary and/or x-only tweaks to the `keyagg_context`
3. You can start a session with the `keyagg_context`. For Schnorr signature verification, you need to get the public key from the `keyagg_context`.

I think to seriously investigate whether forbidding ordinary after x-only tweaking is really simpler, one would need to actually fully modify the BIP draft according to this idea and then directly compare both versions. One could imagine that this change requires introducing new terminology where - in contrast to a Rust implementation - readers don't get the help of a type system.

**Comment by LLFourn** [comment]
Thanks. #15 is a nice improvement. I'll attempt a PR on top of it to apply my suggestion so we can see if it offers a further improvement :)
