### ISSUE TITLE
When should xonly tweaks be used vs "ordinary"

### ISSUE THREAD

**Issue by LLFourn** [jonasnick/bips#13]
Here's something I wasn't able to understand from the text. If I want use BIP86 key derivation on my MuSig key (with some chaincode I chose) How do I first derive `/0/7` (for example) as a non-hardened path and then turn that into an external key.

Do I:
- Apply the `/0` tweak as an ordinary tweak and then `/7` as a XOnly tweak (because I want the resulting internal key to be xonly) and then apply the TR tweak with an xonly tweak.
- Apply both the `/0` tweak and `/7` tweak as ordinary and then apply TR tweak as xonly

I have a feeling we need to somehow simplify things in this spec to have less xonly negating algebra but before suggesting anything I wanted to udnerstand the current API properly. Thanks!

**Comment by jonasnick** [comment]
You need to "Apply both the /0 tweak and /7 tweak as ordinary and then apply TR tweak as xonly". Ordinary tweaking is for BIP32 key derivation and Taproot requires x-only tweaking.

**Comment by real-or-random** [comment]
> I have a feeling we need to somehow simplify things in this spec to have less xonly negating algebra but before suggesting anything

Do you have a specific change in mind?

**Comment by LLFourn** [comment]
Not 

> > I have a feeling we need to somehow simplify things in this spec to have less xonly negating algebra but before suggesting anything
> 
> Do you have a specific change in mind?

No not yet.

**Comment by LLFourn** [comment]
I'll close this in favor of other issues I'm about to open.

**Comment by nickfarrow** [comment]
Semi unrelated but not worthy of new issue: Does anyone know the origin of `ordinary` being used to describe these tweaks?

As someone who is newer to all this, I have found `ordinary` to be slightly misleading. When I hear `ordinary` I think of "the usual" as being the x-only taproot tweak because that is the tweak I am used to. As opposed to ordinary meaning "plain"

**Comment by LLFourn** [comment]
The tweak everyone else is used to is bip32 though :)

**Comment by real-or-random** [comment]
Similar to this discussion: https://github.com/jonasnick/bips/pull/15#discussion_r887233075

@nickfarrow Do you have a better term in mind?

**Comment by nickfarrow** [comment]
Hmm I was thinking `plain` but perhaps `Legacy` is better? maybe pedantic..

**Comment by jonasnick** [comment]
`plain` sounds pretty good imo, but not sure if it's worth changing at this point.

**Comment by real-or-random** [comment]
I also like "plain", it's similar to "ordinary" but a little better. "Ordinary" sounds like the other thing is weird. 

Plain is also a term that would be a good fit for keys itself, so we could 33 byte keys "plain pubkeys".

**Comment by jonasnick** [comment]
Did the rename (for tweaks only) in #29
