### ISSUE TITLE
Include other participants' public nonces in reference tests

### ISSUE THREAD

**Issue by nickfarrow** [jonasnick/bips#14]
Some implementations of MuSig will be easier to test if the reference contains the other party's public nonces, as opposed to the nonces having already been aggregated. If you initialize signing sessions with `[nonce1, nonce2, ... ]` rather than a pre-aggregated `aggnonce`, 

The other two participants' public nonces could be aggregated within the tests themselves, or included in a comment above `aggnonce = ...`. Or in a separate basic test for `nonce_agg()`. This would make both pre-aggregated and nonce-list input designs easy to test.

**Comment by jonasnick** [comment]
Good point. The public nonces are added to the test vectors in PR #9 (e.g. [here](https://github.com/jonasnick/bips/pull/9/files#diff-8910e6ae1aa18a0f6c3da01155f901b1d221761c61c0154b27be4cbbaf18fc8fR456)).

**Comment by real-or-random** [comment]
Solved by #9.
