### ISSUE TITLE
Double superscript

### ISSUE THREAD

**Issue by real-or-random** [jonasnick/bips#18]
The asterisk plus prime is very hard to read.

`* Let ''R<sup>*</sup>' = R<sup>*</sup><sub>1</sub> + b⋅R<sup>*</sup><sub>2</sub>''`

https://github.com/jonasnick/bips/blame/aab260c37112b2010266fd8f0d3d56ea1111a2cc/bip-musig2.mediawiki#L382

Sorry for opening an entire issue for this but I don't have a great suggestion right now

**Comment by robot-dreams** [comment]
Right now we use primed variables mostly to mark "plain" values (that might need to be negated if some public key is odd). Maybe we could use a different convention, such as `R<sub>p</sub>` in place of `R'`.

That being said, this issue might go away on its own depending on how we decide to handle x-only keys in the end.

**Comment by jonasnick** [comment]
While we get rid of the asterisks we could also introduce a more consistent naming scheme for the R-values. Here's a summary of the approaches from the two PRs (as I see them):
```
|     | signer i's nonce j      | this signer's nonce j      | signer i's "effective" nonce   | this signer's effective nonce | final nonce |
|     | nonce_agg               | nonce_gen, partial_sig_ver |                                | partial_sig_ver               | ...         |
|-----+-------------------------+----------------------------+--------------------------------+-------------------------------+-------------|
| #46 | R_{i,j}                 | R_{*,j}                    | not necessary but could be R_i | R_*                           | R           |
| #47 | Rp_{i,j}? (cur R_{i,j}) | Rp_j                       | not necessary  but could be ?  | Rp                            | R           |
```

**Comment by robot-dreams** [comment]
I have a mild preference for #46 because:

- It seems like a less intrusive change
- Replacing R<sub>i,j</sub> with R<sub>⁎,j</sub> to indicate "i is implicit" seems natural
- It avoids the issue of introducing a somewhat arbitrary new naming convention
- It lets us reuse a convention like `Rp` in the future for avoiding primed variables (when deciding whether to negate)

**Comment by jonasnick** [comment]
I noticed that above table misses `R_j` for the aggregate nonce `j` and the naming convention in the paper. Here's an updated table.

```
|                               | paper           | #46     | #47       | suggestion |
|-------------------------------+-----------------+---------+-----------+------------|
| signer i's nonce j            | R_{i,j}         | R_{j,i} | Rp_{j,i}  | R_{i,j}    |
| nonce_agg                     |                 |         |           |            |
|-------------------------------+-----------------+---------+-----------+------------|
| this signer's nonce j         | R_{1,j}         | R_{j,*} | Rp_j      | R_{*,j}    |
| nonce_gen, partial_sig_ver    |                 |         |           |            |
|-------------------------------+-----------------+---------+-----------+------------|
| aggregate nonce j             | R_j             | R_j     | R_j       | R_j        |
| nonce_agg, get_session_values |                 |         |           |            |
|-------------------------------+-----------------+---------+-----------+------------|
| signer i's "effective" nonce  | R^{\hat}_i      | -       | -         | -          |
| (not used in BIP)             |                 |         |           |            |
|-------------------------------+-----------------+---------+-----------+------------|
| this signer's effective nonce | (doesn't exist) | R_*     | Rp        | Re_*       |
| partial_sig_ver               |                 |         |           |            |
|-------------------------------+-----------------+---------+-----------+------------|
| final nonce                   | R               | R       | R         | R          |
```

One can see that in #46 "aggregate nonce j" clashes with "this signer's effective nonce". How about we call the latter `Re_*`?. I'm also slightly in favor of #46 (with this change) since it's a bit more natural (once you understand the meaning of asterisk).

**Comment by jonasnick** [comment]
I fixed the table in my previous comment. It had "signer i's nonce j" wrong for #46 and #47. It's `R_{j,i}` and not `R_{i,j}`.

**Comment by real-or-random** [comment]
I added another suggestion in the table, which uses `Re_*` but also makes `{i,j}` consistent with the paper. Do you think that's good?

**Comment by jonasnick** [comment]
Yup, looks good.
