### ISSUE TITLE
Remove restriction that messages are exactly 32 bytes

### ISSUE THREAD

**Issue by jonasnick** [jonasnick/bips#22]
(as discussed here https://github.com/bitcoin-core/secp256k1/pull/995#issuecomment-1068091437)

**Comment by real-or-random** [comment]
Related: https://github.com/sipa/bips/pull/221

**Comment by real-or-random** [comment]
This has been solved by #24. 

But when working on https://github.com/sipa/bips/pull/221, I realized we should have at least test vector with a message larger than 32 bytes. This will catch implementations that truncate the message at 32 bytes.

**Comment by jonasnick** [comment]
@real-or-random good point. I added test vectors in #52.
