### ISSUE TITLE
Programmatically generate test vectors

### ISSUE THREAD

**Issue by robot-dreams** [jonasnick/bips#49]
The BIP-0340 reference implementation has a [script that programmatically generates the full set of test vectors](https://github.com/bitcoin/bips/blob/master/bip-0340/test-vectors.py). It could be useful to do something similar here in the future, especially to:

- Make the test vectors easier to change in the future, if other parts of the spec change
- Make it more clear to implementers which parts of the input data are "free parameters"

**Comment by real-or-random** [comment]
We think it's not worth the additional work at that stage of the project.
